<!DOCTYPE html>
<html class="lockscreen">
    <head>
        <meta charset="UTF-8">
        <title>.::Quiz App | <?php if(!get_cookie('login_username')) echo 'Admin Login Panel'; else echo 'Lockscreen' ?>::.</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <link href="<?php echo base_url('inc/css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css" />
        <!--<link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" /> -->
        <link href="<?php echo base_url('inc/css/font-awesome.min.css') ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo base_url('inc/css/AdminLTE.css') ?>" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
		<?php if(!get_cookie('login_usernamex')){ ?>
				<div class="form-box" id="login-box">
                    <center><img src="<?php echo base_url('inc/img/logo.png'); ?>" width="100px"></center>
                    <h2 style="color: #fff; margin-bottom: 20px;" class="text-center">Quiz App</h2>
					<div class="header">Admin Login</div>
					<form name="logins" action="<?php echo base_url('admin/login'); ?>" method="post">
						<div class="body bg-gray">
							<!-- to show error -->
							<?php if(isset($error_msg)){ ?>
							<div class="alert alert-danger alert-dismissable">
								<i class="fa fa-ban"></i>
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								<?php echo validation_errors(); ?>
							</div>
							<?php } ?>
							<div class="form-group">
								<input type="text" class="form-control" placeholder="username" name="user_name" value="<?php echo set_value('user_name'); ?>" />
							</div>
							<div class="form-group">
								<input type="password" class="form-control" placeholder="password" name="user_pass" value="<?php echo set_value('user_pass'); ?>" />
							</div>
						</div>
						<div class="footer">
							<button type="submit" class="btn bg-light-blue btn-block">Sign me in</button>
                            <p>
                                <a href="<?php echo base_url('user'); ?>">Are you a participant? Click here.</a>
                            </p>

						</div>
					</form>
				</div>
		<?php  }else{	?>
        <!-- Automatic element centering using js -->
        <div class="center">
            <div class="headline text-center" id="time">
                <!-- Time auto generated by js -->
            </div><!-- /.headline -->

			<!-- to show error -->
			<?php if(isset($error_msg)){ ?>
			<div class="alert alert-danger alert-dismissable">
				<i class="fa fa-ban"></i>
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				<?php echo validation_errors(); ?>
			</div>
			<?php } ?>
			

            <!-- START LOCK SCREEN ITEM -->
			<form name="logins" action="<?php echo base_url('login'); ?>" method="post">
				<!-- User name -->
				<div class="lockscreen-name"><?php echo $user_fullname ?></div>
				<div class="lockscreen-item">
					<!-- lockscreen image -->
					<div class="lockscreen-image">
						<img src="<?php echo base_url('inc/img/'.$user_pic); ?>" alt="user image"/>
					</div>
					<!-- /.lockscreen-image -->

					<!-- lockscreen credentials (contains the form) -->
					<div class="lockscreen-credentials">
						
						
						<input type="hidden" class="form-control" placeholder="username" name="user_name" value="<?php echo set_value('user_name',get_cookie('login_username')); ?>" />
			
						
						<div class="input-group">
							<input type="password" class="form-control" placeholder="password" name="user_pass" value="<?php echo set_value('user_pass'); ?>" />
							<div class="input-group-btn">
								<button class="btn btn-flat"><i class="fa fa-arrow-right text-muted"></i></button>
							</div>
						</div>
					</div><!-- /.lockscreen credentials -->
				</div><!-- /.lockscreen-item -->
			</form>									
									
            <div class="lockscreen-link">
                <a href="<?php echo base_url('logout2'); ?>">Or sign in as a different user</a>
            </div>
			<?php }	?>

        </div><!-- /.center -->

        <script src="<?php echo base_url('inc/js/jquery.min.js'); ?>"></script>
        <script src="<?php echo base_url('inc/js/bootstrap.min.js'); ?>" type="text/javascript"></script>

        <!-- page script -->
        <script type="text/javascript">
            $(function() {
                startTime();
                $(".center").center();
                $(window).resize(function() {
                    $(".center").center();
                });
            });

            /*  */
            function startTime()
            {
                var today = new Date();
                var h = today.getHours();
                var m = today.getMinutes();
                var s = today.getSeconds();

                // add a zero in front of numbers<10
                m = checkTime(m);
                s = checkTime(s);

                //Check for PM and AM
                var day_or_night = (h > 11) ? "PM" : "AM";

                //Convert to 12 hours system
                if (h > 12)
                    h -= 12;

                //Add time to the headline and update every 500 milliseconds
                $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
                setTimeout(function() {
                    startTime()
                }, 500);
            }

            function checkTime(i)
            {
                if (i < 10)
                {
                    i = "0" + i;
                }
                return i;
            }

            /* CENTER ELEMENTS IN THE SCREEN */
            jQuery.fn.center = function() {
                this.css("position", "absolute");
                this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                        $(window).scrollTop()) - 30 + "px");
                this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                        $(window).scrollLeft()) + "px");
                return this;
            }
        </script>
    </body>
</html>
